module MenuStruct

  # set of structs to describe a menu tree
  
  # Menu represents a menu populated with Rows
  # :prompt is a string for static text, or a symbol if generated by a method
  #   represents the message at the top of the menu view
  # :rows is an array of Row structs, or a proc for Rows generated by a method
  #   represents all the rows to scroll through and select from
  Menu = Struct.new(:prompt, :rows)

  # Row represents the contents of one menu row
  # :text is a string for static text, or a symbol if generated by a method
  #   represents the text the user will see in the row
  # :action is a new Menu struct for a nested menu, a symbol corresponding
  # to a method, or an array with a method-symbol and arguments
  #   represents what happens when the row is selected
  Row = Struct.new(:text, :action)
  
  # RowsOf represents a number of rows generated from a set of data with a proc
  # :formatter is a procedure that formats the given data into rows
  # :data_set is a symbol that tells an outside method what data to fetch for proc
  # :filter is a string to narrow the data set, such as albums for "ArtistX", 
  #   instead of all albums
  RowsOf = Struct.new(:formatter, :data_set, :filter)
  
end
