module MenuStruct

  # Menu represents a menu populated with Rows
  # :heading is a string for static text, or a symbol if generated by a method
  # :rows is an array of Row structs, or a proc for Rows generated by a method 
  Menu = Struct.new(:prompt, :rows)

  # Row represents the contents of one menu row
  # :text is a string for static text, or a symbol if generated by a method
  # :action is a new Menu struct for a nested menu, a symbol corresponding
  # to a method, or an array with a method-symbol and arguments
  Row = Struct.new(:text, :action)
  
  # RowsOf represents a number of rows generated from a set of data with a proc
  # :formatter is a procedure that formats the given data into rows
  # :data_set is a symbol that tells an outside method what data to fetch for proc
  # :filter is a string to narrow the data set, such as albums for "ArtistX", 
  #   instead of all albums
  RowsOf = Struct.new(:formatter, :data_set, :filter)
  
end
